# Generated by Django 5.2.6 on 2025-10-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0002_client_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='nom_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='nom_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='nombre_personnes_en',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='nombre_personnes_fr',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='numero_en',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='table',
            name='numero_fr',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
